### ISSUE TITLE
rwb static error

### ISSUE THREAD

**Issue by resistdesign** [petehunt/react-cli#12]
When running `rwb static` there is an error: `Invariant Violation: You do not have a loader that handles files with the extension: json`.

**Comment by elliottkember** [comment]
I have this, too. Tried installing json-loader but that didn't help.

**Comment by petehunt** [comment]
@meyer is on the case

**Comment by elliottkember** [comment]
@meyer is the best

**Comment by resistdesign** [comment]
Yey @meyer !

**Comment by meyer** [comment]
so much pressure :sweat:

**Comment by resistdesign** [comment]
Oops did not mean to close.

@meyer I made my own fork and applied your commit and now I get this:

``` bash
$: rwb static

/Users/***/.nvm/versions/node/v4.2.2/lib/node_modules/rwb/node_modules/style-loader/addStyles.js:30
        if (typeof options.singleton === "undefined") options.singleton = isOldIE();
^
ReferenceError: window is not defined
    at /Users/***/.nvm/versions/node/v4.2.2/lib/node_modules/rwb/node_modules/style-loader/addStyles.js:14:1
    at /Users/***/.nvm/versions/node/v4.2.2/lib/node_modules/rwb/node_modules/style-loader/addStyles.js:9:1
    at e.exports (/Users/***/.nvm/versions/node/v4.2.2/lib/node_modules/rwb/node_modules/style-loader/addStyles.js:30:1)
    at Object.<anonymous> (webpack:///MyComponent.css?12a2:7:1)
    at t (webpack/bootstrap f9215b977c34d7bcad1b:9:1)
    at Object.<anonymous> (bundle.js:13877:24)
    at Object.<anonymous> (bundle.js:14157:28)
    at t (webpack/bootstrap f9215b977c34d7bcad1b:9:1)
    at Object.<anonymous> (bundle.js:14694:21)
    at Object.<anonymous> (bundle.js:14703:28)
```

**Comment by meyer** [comment]
@resistdesign yeeep, I was a little overzealous in copying the `serve` loaders over. Sorry about that.

**Comment by resistdesign** [comment]
@meyer np, it's all part of the process! :)

**Comment by resistdesign** [comment]
@meyer Just tried your fork at master and it worked a bit better but I'm referring to `window` in my app code so now I get:

``` bash
const CURRENT_PROTOCOL = window.location.protocol;
                         ^
ReferenceError: window is not defined
```

Is that just a global that needs to be set in webpack? New issue time?

**Comment by petehunt** [comment]
@resistdesign `window` is not set on purpose. Since `rwb` is an implementation of "isomorphic" JS, you may not have access to the browser APIs at load time.

Think about it: during the static build step, what should `window.location.protocol` return? Since it's not being run in an actual web page served from a web server, there's no `location.protocol`. Instead, you can refer to `window` in React lifecycle hooks that only run in the browser (i.e. `componentDidMount()`).

**Comment by resistdesign** [comment]
ah ok!

**Comment by resistdesign** [comment]
I did not know isomorphic was a goal for this :)
