### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by hnordt** [petehunt/react-cli#16]
Hello. Thank you for this great way to build React projects. :+1: :+1: :+1: 

I'm using Cloud9, so I tried:

`RWB_PORT=$PORT RWB_PUBLIC_URL=http://$IP/ rwb serve`

Then I received this error in console:

`XMLHttpRequest cannot load http://dev-hnordt.c9.io/fd659a8394f48eb37284.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev-hnordt.c9.io:8080' is therefore not allowed access.`

Would be great to have CORS enabled.

**Comment by resistdesign** [comment]
@hnordt CORS is something you enable on the server. The browser is looking for the server to return a few headers, the main header being `Access-Control-Allow-Origin`. There are a couple more as well, typically: `['Accept', 'Authorization', 'Content-Type']`. If your server app is based on Express or Koa there are already some `npm` modules that will help you manage the CORS headers.

**Comment by resistdesign** [comment]
@hnordt Sorry, I messed up, 'Accept', 'Authorization' and 'Content-Type' are typical headers the server says it will accept via the `Access-Control-Allow-Headers` header.
