### ISSUE TITLE
React 0.14?

### ISSUE THREAD

**Issue by wookiehangover** [petehunt/react-cli#18]
Howdy!

Really dig the project, but I was wondering if there's any particular reason why you're defaulting to React v0.13?

I'd be happy to make (and test) a PR to update this if it's welcome :smiley_cat: 

✌️

**Comment by petehunt** [comment]
I'd love a PR for this!

**Comment by bobzoller** [comment]
seems like this can be closed -- I installed fresh and got react 0.14.7, and everything works fine except for the (I think unrelated) #23.

**Comment by petehunt** [comment]
thank yoU!
