### ISSUE TITLE
rwb static writes bundle.js and styles.css to system root directory

### ISSUE THREAD

**Issue by petermoresi** [petehunt/react-cli#5]
Running `rwb static` I'm getting an access error on /bundle.js. Is

~/p/Test> rwb static
The unused option is deprecated. Please use options.discardUnused instead.
The urls option is deprecated. Please use options.normalizeUrl instead.
The idents option is deprecated. Please use options.mergeIdents instead.
The idents option is deprecated. Please use options.reduceIdents instead.
{ [Error: EACCES, open '/bundle.js'] errno: -13, code: 'EACCES', path: '/bundle.js' }

I ran it again as sudo. The bundle.js and styles.css were both created in the root directory.

**Comment by petermoresi** [comment]
I tracked this issue to https://github.com/petehunt/webpack-require/blob/master/lib/webpackRequire.js at line # 59

**Comment by petehunt** [comment]
nice catch -- fixed it

**Comment by petermoresi** [comment]
Thanks for fixing this. This helps a lot.
